---
roles:
  - src: stackhpc.nfs
    version: v22.9.1
  - src: https://github.com/stackhpc/ansible-role-openhpc.git
    version: v0.20.0 # Allow multiple empty partitions by @sjpb in #156
    name: stackhpc.openhpc
  - src: https://github.com/stackhpc/ansible-node-exporter.git
    version: feature/no-install
    name: cloudalchemy.node_exporter
  - src: cloudalchemy.alertmanager
    version: 0.19.1
  - src: https://github.com/stackhpc/ansible-grafana.git
    name: cloudalchemy.grafana
    version: service-state
    # No versions available
  - src: https://github.com/OSC/ood-ansible.git
    name: osc.ood
    version: v2.0.8

collections:
- name: containers.podman
- name: community.grafana
- name: https://github.com/stackhpc/ansible_collection_slurm_openstack_tools
  type: git
  version: v0.2.0
- name: prometheus.prometheus
  version: 0.5.1
...
